spring:
  application:
    name: stream
  rabbitmq:
    addresses: amqp://192.168.36.129:5772
    username:  user
    password: 123456


  cloud:
    stream:
      bindings:
         input:
           group: Service-A
           destination: greetings
           consumer:
             partitioned: true
      instanceCount: 1
      instanceIndex: 0

server:
  port: 8189

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8181/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}